In [1]:
import numpy as np

array1 = np.array([[[11,12,13,14,15],[21,22,23,24,25]],[[0,31,32,33,34],[41,42,43,44,45]]])
print(array1)


[[[11 12 13 14 15]
  [21 22 23 24 25]]

 [[ 0 31 32 33 34]
  [41 42 43 44 45]]]


In [2]:
print(type(array1))
print(array1.ndim)



<class 'numpy.ndarray'>
3


In [3]:
array2 = np.array([[1,2,3,4,5],[1,2,3,4,6]])
print(array2)
print(type(array2))
print(array2.ndim)
print("\n")


[[1 2 3 4 5]
 [1 2 3 4 6]]
<class 'numpy.ndarray'>
2




In [4]:
arr3 = np.array([1,2,3,4,5])
print(arr3)
print(type(arr3))
print(arr3.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
arrayZerosFiveFive = np.zeros((5,5), dtype=float)
print(arrayZerosFiveFive)
print("\n")
arrayZerosThreeTwo = np.zeros((3,2),dtype=bool)
print(arrayZerosThreeTwo)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[False False]
 [False False]
 [False False]]


In [7]:
arrayRange = np.arange(1,30,4.3, dtype=float)
print(arrayRange)

[ 1.   5.3  9.6 13.9 18.2 22.5 26.8]


In [8]:
data = np.array([['','Sachin','Tendulkar'],['Roger',45,'Federer'],['LeBron James',3,4]])
print(data)
print(data[0][1])

#retrieves 3rd column from all rows
data[:2]

[['' 'Sachin' 'Tendulkar']
 ['Roger' '45' 'Federer']
 ['LeBron James' '3' '4']]
Sachin


array([['', 'Sachin', 'Tendulkar'],
       ['Roger', '45', 'Federer']], dtype='<U12')

In [12]:
#converting list,tuples and dictionaries to numpy array

list1 = ["paris","NY","Dehli","India"]
print(type(list1),end="End of list 1 \n ")
tuple1 = ('dog','cat','bat')
print(type(tuple1),end=",")
dictionary = {0:'Zero',1:'One',2:'Two', 3:'Three'}
print(type(dictionary),'\n')
print('-------------------------------------------------------------\n')
arr3 = np.array(list1)
print(arr3,type(arr3),'\n')
arr4 = np.array(tuple1)
print(arr4,type(arr4),'\n')


<class 'list'>End of list 1 
 <class 'tuple'>,<class 'dict'> 

-------------------------------------------------------------

['paris' 'NY' 'Dehli' 'India'] <class 'numpy.ndarray'> 

['dog' 'cat' 'bat'] <class 'numpy.ndarray'> 



In [14]:
#reshaping 1d array (i.e. tuple1 to 1d array) to 2d array
arr4_2dimesional = arr4.reshape(3,1)
print(arr4_2d,'\n','The dimensions of arr4 after reshaping is :',arr4_2d.ndim)
arr4_2d[:,0]
print(arr4_2d[0][0],'&',arr4_2d[1][0],'&',arr4_2d[2][0])

#dictionary to numpy array

result = dictionary.items()
data = list(result)
ndarray=np.array(data)

print('\ndict to array is :\n',ndarray)
print('\n',ndarray.ndim)
print('\n',type(ndarray))
print('\n',type(dictionary))

[['dog']
 ['cat']
 ['bat']] 
 The dimensions of arr4 after reshaping is : 2
dog & cat & bat

dict to array is :
 [['0' 'Zero']
 ['1' 'One']
 ['2' 'Two']
 ['3' 'Three']]

 2

 <class 'numpy.ndarray'>

 <class 'dict'>


In [2]:
import pandas as pd

In [3]:
#creating dataframe from various data types

#from dictionary
data = {"Names":["Jack Ma","Brandon","Liza","Musk"],'Rankings':[250,10,320,650],'cost':[103,220,3450,140]}
df3 = pd.DataFrame(data)
df3



Names  Rankings  cost
0  Jack Ma       250   103
1  Brandon        10   220
2     Liza       320  3450
3     Musk       650   140

In [11]:

NbaAllSeasonsData = pd.read_csv('all_seasons.csv',index_col=0)
NbaAllSeasonsData.head(10)


player_name team_abbreviation   age  player_height  player_weight  \
0      Dennis Rodman               CHI  36.0         198.12      99.790240   
1  Dwayne Schintzius               LAC  28.0         215.90     117.933920   
2       Earl Cureton               TOR  39.0         205.74      95.254320   
3        Ed O'Bannon               DAL  24.0         203.20     100.697424   
4        Ed Pinckney               MIA  34.0         205.74     108.862080   
5      Eddie Johnson               HOU  38.0         200.66      97.522280   
6        Eddie Jones               LAL  25.0         198.12      86.182480   
7     Elden Campbell               LAL  28.0         213.36     113.398000   
8  Eldridge Recasner               ATL  29.0         193.04      86.182480   
9       Elliot Perry               MIL  28.0         182.88      72.574720   

                       college country draft_year draft_round draft_number  \
0  Southeastern Oklahoma State     USA       1986           2           27   
1                      Florida     USA       1990           1           24   
2                Detroit Mercy     USA       1979           3           58   
3                         UCLA     USA       1995           1            9   
4                    Villanova     USA       1985           1           10   
5                     Illinois     USA       1981           2           29   
6                       Temple     USA       1994           1           10   
7                      Clemson     USA       1990           1           27   
8                   Washington     USA       1992   Undrafted    Undrafted   
9                      Memphis     USA       1991           2           37   

   ...   pts   reb  ast  net_rating  oreb_pct  dreb_pct  usg_pct  ts_pct  \
0  ...   5.7  16.1  3.1        16.1     0.186     0.323    0.100   0.479   
1  ...   2.3   1.5  0.3        12.3     0.078     0.151    0.175   0.430   
2  ...   0.8   1.0  0.4        -2.1     0.105     0.102    0.103   0.376   
3  ...   3.7   2.3  0.6        -8.7     0.060     0.149    0.167   0.399   
4  ...   2.4   2.4  0.2       -11.2     0.109     0.179    0.127   0.611   
5  ...   8.2   2.7  1.0         4.1     0.034     0.126    0.220   0.541   
6  ...  17.2   4.1  3.4         4.1     0.035     0.091    0.209   0.559   
7  ...  14.9   8.0  1.6         3.3     0.095     0.183    0.222   0.520   
8  ...   5.7   1.6  1.3        -0.3     0.036     0.076    0.172   0.539   
9  ...   6.9   1.5  3.0        -1.2     0.018     0.081    0.177   0.557   

   ast_pct   season  
0    0.113  1996-97  
1    0.048  1996-97  
2    0.148  1996-97  
3    0.077  1996-97  
4    0.040  1996-97  
5    0.102  1996-97  
6    0.149  1996-97  
7    0.087  1996-97  
8    0.141  1996-97  
9    0.262  1996-97  

[10 rows x 21 columns]

In [12]:

playerNameAge = pd.DataFrame(data1,columns=['player_name','age'])
print(playerNameAge)

              player_name   age
0           Dennis Rodman  36.0
1       Dwayne Schintzius  28.0
2            Earl Cureton  39.0
3             Ed O'Bannon  24.0
4             Ed Pinckney  34.0
...                   ...   ...
11140         Maxi Kleber  28.0
11141  Melvin Frazier Jr.  23.0
11142      Meyers Leonard  28.0
11143        Norvel Pelle  27.0
11144         Matt Thomas  25.0

[11145 rows x 2 columns]
